### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by 2000jedi** [trailofbits/pasta#64]
Hi, when I am trying to build pasta, I have already made cxx-common available, the following error is emitted:

```
pasta/lib/AST/Attr.cpp:62:5: error: no member named 'HLSLGroupSharedAddressSpace' in 'clang::attr::Kind'
```

**Comment by pgoodman** [comment]
What version of cxx-common, and for what llvm version? PASTA requires the llvm-16-pasta version of cxx-common. What options are you using when configuring?

**Comment by 2000jedi** [comment]
I am using the same environment VAST is using, so probably cmake finds the LLVM 15 and clang 15 that were used to build VAST. I am trying to build it on a clean docker container. Hopefully it would work this time.

**Comment by 2000jedi** [comment]
@pgoodman One issue I observe in the README is that the linux build script indicates the `x64-osx-rel` triplet, while I presume we should use `x64-linux-rel`

**Comment by 2000jedi** [comment]
I am using the `cxx-common` provided in the build instruction, while the compilation indicates that the file `clang/Lex/PPCallbacksEventKind.h` is not found. I have verified that this file is not in the vcpkg installation.

**Comment by pgoodman** [comment]
I have updated the README to reflect that LLVM 16 must be used. I recommend downloading this release: https://github.com/lifting-bits/cxx-common/releases/download/v0.3.1/vcpkg_ubuntu-22.04_llvm-16-pasta_amd64.tar.xz

**Comment by 2000jedi** [comment]
There is still an error when building on Ubuntu which occurs using both clang-10 and clang-12:
```
FAILED: CMakeFiles/pasta_compiler.dir/lib/AST/Token.cpp.o
/usr/bin/clang++-12 -D_GNU_SOURCE -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/pasta/build/lib/Compile -I/home/pasta/include -isystem /root/vcpkg_ubuntu-22.04_llvm-16-pasta_amd64/installed/x64-linux-rel/include -O2 -g -DNDEBUG -std=c++20 -fvisibility-inlines-hidden -Wall -pedantic -Wconversion -Wno-unknown-pragmas -MD -MT CMakeFiles/pasta_compiler.dir/lib/AST/Token.cpp.o -MF CMakeFiles/pasta_compiler.dir/lib/AST/Token.cpp.o.d -o CMakeFiles/pasta_compiler.dir/lib/AST/Token.cpp.o -c /home/pasta/lib/AST/Token.cpp
/home/pasta/lib/AST/Token.cpp:501:10: error: calling a protected constructor of class 'pasta::DefineMacroDirective'
  return DefineMacroDirective(ast, &(node_it->second));
```

**Comment by pgoodman** [comment]
Try with latest master branch.

**Comment by 2000jedi** [comment]
They are working now. I also updated to `clang-14`. I think neither `clang-10` nor `clang-12` works.
